### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by GKaszewski** [devildefu/pb_battleroyale#2]
CMakeFiles/pb_battleroyale.dir/src/spdlog.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
error adding symbols: DSO missing from command line

**Comment by Firstbober** [comment]
Add -pthread in CMakeLists.txt.
I already fixed it in my fork.

**Comment by devildefu** [comment]
Do you use linux?

**Comment by devildefu** [comment]
Yeah, I didn't get this error because I use Windows, Firstbober as he wrote, he fixed it.
